# -*- coding: utf-8 -*-
"""lesson1_practice_pandas_titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkQtpcheqPAT4hq2KmAQWaCQdzWUmDou

# Дз № 1

<center>
<img src="../../img/ods_stickers.jpg">
## Открытый курс по машинному обучению. Сессия № 2
</center>
Автор материала: программист-исследователь Mail.ru Group, старший преподаватель Факультета Компьютерных Наук ВШЭ Юрий Кашницкий. Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

# <center>Тема 1. Первичный анализ данных с Pandas</center>
## <center>Практическое задание. Анализ данных пассажиров "Титаника"</center>

**Заполните код в клетках (где написано "Ваш код здесь") и ответьте на вопросы в [веб-форме](https://goo.gl/SbRcpW).**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
pd.set_option("display.precision", 2)
# %matplotlib inline

"""**Считаем данные из файла в память в виде объекта Pandas.DataFrame**"""

data = pd.read_csv("titanic_train.csv", index_col="PassengerId")

"""**Данные представлены в виде таблицы. Посмотрим на первые 5 строк:**"""

data.head(6)

data.describe()

"""**Для примера отберем пассажиров, которые сели в Cherbourg (Embarked=C) и заплатили более 200 у.е. за билет (fare > 200).**

Убедитесь, что Вы понимаете, как эта конструкция работает. <br>
Если нет – посмотрите, как вычисляется выражение в квадратных в скобках.
"""

data[(data["Embarked"] == "C") & (data["Fare"] > 200)].head()

"""**Можно отсортировать этих людей по убыванию платы за билет.**"""



"""**Пример создания признака.**"""

def age_category(age):
    """
    < 30 -> 1
    >= 30, <55 -> 2
    >= 55 -> 3
    """
    if age < 30:
        return 1
    elif age < 55:
        return 2
    else:
        return 3

age_categories = [age_category(age) for age in data.Age]

data["Age_category"] = age_categories

"""**Другой способ – через `apply`.**"""

data["Age_category"] = data["Age"].apply(age_category)

"""**1. Сколько мужчин / женщин находилось на борту?**
- 412 мужчин и 479 женщин
- 314 мужчин и 577 женщин
- 479 мужчин и 412 женщин
- 577 мужчин и 314 женщин
"""

data[data["Sex"] == "female"].count()

"""**2. Выведите распределение переменной `Pclass` (социально-экономический статус) и это же распределение, только для мужчин / женщин по отдельности. Сколько было мужчин 2-го класса?**
- 104
- 108
- 112
- 125
"""

pd.crosstab(data['Pclass'], data['Sex'], margins=True)

"""**3. Каковы медиана и стандартное отклонение платежей (`Fare`)? Округлите до 2 десятичных знаков.**
- Медиана – 14.45, стандартное отклонение – 49.69
- Медиана – 15.1, стандартное отклонение – 12.15
- Медиана – 13.15, стандартное отклонение – 35.3
- Медиана – 17.43, стандартное отклонение – 39.1
"""

print(data["Fare"].median(),data["Fare"].std())

"""**4. Правда ли, что люди моложе 30 лет выживали чаще, чем люди старше 60 лет? Каковы доли выживших в обеих группах?**
- 22.7% среди молодых и 40.6% среди старых
- 40.6% среди молодых и 22.7% среди старых
- 35.3% среди молодых и 27.4% среди старых
- 27.4% среди молодых и 35.3% среди старых
"""

young_survived = data[data['Age'] < 30]['Survived']
print(round(young_survived.mean() * 100, 1))
young_survived = data[data['Age'] > 60]['Survived']
print(round(young_survived.mean() * 100, 1))

"""**5. Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших в обеих группах?**
- 30.2% среди мужчин и 46.2% среди женщин
- 35.7% среди мужчин и 74.2% среди женщин
- 21.1% среди мужчин и 46.2% среди женщин
- 18.9% среди мужчин и 74.2% среди женщин
"""

young_survived = data[data['Sex'] == "male"]['Survived']
print(round(young_survived.mean() * 100, 1))
young_survived1= data[data['Sex'] == "female"]['Survived']
print(round(young_survived1.mean() * 100, 1))

"""**6. Найдите самое популярное имя среди пассажиров Титаника мужского пола?**
- Charles
- Thomas
- William
- John
"""

data[data['Sex'] == 'male']['Name'].apply(lambda full_name: full_name.split(',')[1].split()[1]).value_counts().head()

"""**7. Сравните графически распределение стоимости билетов и возраста у спасенных и у погибших. Средний возраст погибших выше, верно?**
- Да
- Нет
"""

data[data['Survived'] == 1]['Fare'].hist(color="green",
                                         label='Survived')
data[data['Survived'] == 0]['Fare'].hist(color="red",
                                         label='Died')
plt.title('Ticket fare for survived and died')
plt.xlabel('Pounds')
plt.ylabel('Frequency')
plt.legend();
data.groupby('Survived')['Age'].mean()

"""**8. Как отличается средний возраст мужчин / женщин в зависимости от класса обслуживания? Выберите верные утверждения:**
- В среднем мужчины 1-го класса старше 40 лет
- В среднем женщины 1-го класса старше 40 лет
- Мужчины всех классов в среднем старше женщин того же класса
- В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса
"""

pd.crosstab(data['Pclass'], data['Sex'],
            values=data['Age'], aggfunc=np.mean)

# Ваш код здесь